language: java

# see https://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure
sudo: false

# Отправлять уведомление на почту krylov.sergey.1999@yandex.ru если сборка упала
notifications:
  email:
    recipients:
      - krylov.sergey.1999@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always

script:
  - ./gradlew build --scan -s

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/